name: Bump and Tag

on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  contents: write

jobs:
    bump:
      # Only run if the PR was closed & merged
      if: github.event.pull_request.merged == true
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            ref: ${{ github.event.pull_request.merge_commit_sha }}

        - name: Bump And Tag
          uses: Tether-Payments/github-bump-and-tag@v0.1.0
